---
title: "Dissertation Pilot Information"
author: "Dave Braun"
date: "7/10/2019"
knit: (function(inputFile, encoding){
        rmarkdown::render(inputFile, 
                          encoding = encoding,
                          output_file = 'index.html')})
---

Hello!

Thank you for piloting my study. I’m hoping this pilot will take you around **30 minutes** to complete and hopefully not longer than 60 minutes. The timing is something I'm hoping to get a better handle on from your data, so please bear with me for now!

## How to Perform the Experiment

### Basic Concepts

Because I'm running this study on Amazon's Mechanical Turk (ie, MTurk), you'll need to have or create an MTurk Worker account. MTurk is basically a marketplace for labor run by Amazon. There are *requesters* who post what are called Human Intelligence Tasks (HITS, i.e., experiments), and there are workers who get paid to perform the HITs. In this scenario, I'm the requester and you're the worker, except, sadly, you won't be earning any money. You will be paid in a healthy amount of gratitude, however. I’m testing this experiment in the Mturk “sandbox” (ie, development platform), so that's where you'll need to go once you've made an account.

### What to do:
  
1. First make an account (or sign in) by going here: https://workersandbox.mturk.com  
    * Be sure that you're logging into the **sandbox** and not the regular MTurk marketplace.

2. Then find the experiment in the list of existing HITs
    * You should be able to pretty easily find it by searching "Braun Decision Making Experiment" in the MTurk **sandbox** marketplace.
    
3. Complete the experiment

    * It should hopefully be self explanatory. Make sure to watch the instructional videos--I'd welcome your feedback as to whether or not you thought they were clear enough to know what you're supposed to be doing in the experiment.
  
    * Once you get to the end of the experiment, it’ll ask you to fill out some demographic info and there will be a box for comments. It would be super helpful if in that comment box you could put:
  
      * Your name   
        * I know, I technically can’t ask this of you, but if I go back and see something weird in your data it would be helpful for me to be able to ask you a question about it directly. But if you don’t want to put your name by all means don’t.  
      * Did you encounter any bugs / programming errors?  
      * Whether the instructions were clear / was there anything you didn’t understand.  
      * About how long the whole thing took you from start to finish.  
      * Any other comments or things you think I should change.  

### Other notes
  
* If there's a bug so bad that causes you to not be able to reach the end of the experiment, please email me (dab414@lehigh.edu) and try to describe to me as exactly as possible what happened. I'll need to fix every possible error before this thing lauches. Unanticipated bugs are the type of things that keep me up at night.

* I’ve tested this experiment myself pretty thoroughly, but this type of browser experiment is relatively new territory for me. If anything feels weird at all, please let me know! Please email me (dab414@lehigh.edu) after you’ve completed the experiment, so I know that everyone who completed the experiment is showing up in the data.

Best,  
Dave